version: '3.7'
services:
  terraform:
    command: plan -out=/instant-jellyfin/.tfplan
    environment:
      - TF_VAR_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - TF_VAR_AWS_REGION=$AWS_REGION
      - TF_VAR_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - TF_VAR_EBS_ROOT_VOLUME_SIZE=$EBS_ROOT_VOLUME_SIZE
      - TF_VAR_EBS_MEDIA_VOLUME_SIZE=$EBS_MEDIA_VOLUME_SIZE
      - TF_VAR_EBS_MEDIA_VOLUME_TYPE=$EBS_MEDIA_VOLUME_TYPE
      - TF_VAR_EC2_INSTANCE_TYPE=$EC2_INSTANCE_TYPE
      - TF_VAR_ENVIRONMENT=$ENVIRONMENT
      - TF_VAR_HOSTED_ZONE_ID=$HOSTED_ZONE_ID
    build:
      context: .
      dockerfile: ./Dockerfile.terraform
    volumes:
      - type: bind
        source: ./
        target: /instant-jellyfin
    tty: true
    stdin_open: true